import React, { useState, useEffect } from 'react';
import {
  Play,
  Film,
  Link as LinkIcon,
  Key,
  Github,
  CheckCircle2,
  AlertCircle,
  Clock,
  Send,
  Database,
  Layers,
  FileCode,
  Copy,
  Check,
  ExternalLink,
  Eye,
  EyeOff,
  Terminal,
  Server,
  RefreshCw,
  Sparkles,
  Download
} from 'lucide-react';

interface DispatchHistoryItem {
  id: string;
  tmdbId: string;
  sourceUrl: string;
  timestamp: string;
  status: 'queued' | 'error' | 'simulated';
  repo: string;
  message?: string;
}

interface TMDbPreview {
  id: string;
  title: string;
  releaseDate: string;
  overview: string;
  posterUrl?: string;
  mediaType: string;
}

const PRESET_DEMOS = [
  { id: '157336', title: 'Interstellar (2014)', url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4' },
  { id: '27205', title: 'Inception (2010)', url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4' },
  { id: '550', title: 'Fight Club (1999)', url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4' },
];

const SUPABASE_SCHEMA_SQL = `-- Supabase Movies Table Definition
create table if not exists public.movies (
  id bigint generated by default as identity primary key,
  tmdb_id bigint not null unique,
  title text not null,
  overview text,
  poster_path text,
  release_date text,
  servers jsonb default '[]'::jsonb,
  download_url text,
  created_at timestamptz default timezone('utc'::text, now()) not null,
  updated_at timestamptz default timezone('utc'::text, now()) not null
);

-- Index on tmdb_id for lightning-fast upsert queries
create index if not exists idx_movies_tmdb_id on public.movies(tmdb_id);

-- Optional Row Level Security (RLS)
alter table public.movies enable row level security;
create policy "Allow read access to all users" on public.movies for select using (true);
create policy "Allow service role full access" on public.movies for all using (auth.role() = 'service_role');
`;

const GITHUB_WORKFLOW_CODE = `name: Automated Media Processing Pipeline

on:
  repository_dispatch:
    types: [process_video]
  workflow_dispatch:
    inputs:
      tmdb_id:
        description: 'TMDb Movie/Show ID (e.g. 157336)'
        required: true
        type: string
      source_url:
        description: 'Direct Source Video URL'
        required: true
        type: string

jobs:
  process-and-ingest:
    name: Transcode & Ingest Media
    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install System Dependencies (FFmpeg & aria2c)
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends ffmpeg aria2

      - name: Verify CLI Tools
        run: |
          ffmpeg -version | head -n 1
          aria2c --version | head -n 1

      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp requests python-telegram-bot supabase

      - name: Execute Media Processing Engine
        env:
          TELEGRAM_BOT_TOKEN: \${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: \${{ secrets.TELEGRAM_CHANNEL_ID }}
          SUPABASE_URL: \${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: \${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          TMDB_API_KEY: \${{ secrets.TMDB_API_KEY }}
          TMDB_ID: \${{ github.event.client_payload.tmdb_id || github.event.inputs.tmdb_id }}
          SOURCE_URL: \${{ github.event.client_payload.source_url || github.event.inputs.source_url }}
        run: |
          python process.py
`;

export default function App() {
  // Input fields per prompt specification
  const [tmdbId, setTmdbId] = useState('');
  const [sourceUrl, setSourceUrl] = useState('');
  const [githubPat, setGithubPat] = useState('');
  
  // Repo target configuration
  const [repoOwner, setRepoOwner] = useState('');
  const [repoName, setRepoName] = useState('');
  
  // UI state
  const [showPat, setShowPat] = useState(false);
  const [activeTab, setActiveTab] = useState<'console' | 'architecture' | 'files' | 'supabase'>('console');
  const [selectedFileTab, setSelectedFileTab] = useState<'workflow' | 'process_py' | 'standalone_html' | 'sql'>('workflow');
  
  // Submission & notification status
  const [status, setStatus] = useState<{
    type: 'idle' | 'loading' | 'success' | 'error';
    title: string;
    description: string;
    payload?: any;
    httpCode?: number;
  }>({
    type: 'idle',
    title: '',
    description: '',
  });

  const [copiedKey, setCopiedKey] = useState<string | null>(null);
  const [history, setHistory] = useState<DispatchHistoryItem[]>([]);
  const [isSimulating, setIsSimulating] = useState(false);
  const [simulationLog, setSimulationLog] = useState<string[]>([]);
  
  // TMDb preview cache
  const [tmdbPreview, setTmdbPreview] = useState<TMDbPreview | null>(null);

  // Load persisted values on mount
  useEffect(() => {
    const savedOwner = localStorage.getItem('media_repo_owner') || '';
    const savedRepo = localStorage.getItem('media_repo_name') || '';
    const savedPat = localStorage.getItem('media_repo_pat') || '';
    const savedHistory = localStorage.getItem('media_dispatch_history');

    if (savedOwner) setRepoOwner(savedOwner);
    if (savedRepo) setRepoName(savedRepo);
    if (savedPat) setGithubPat(savedPat);
    if (savedHistory) {
      try {
        setHistory(JSON.parse(savedHistory));
      } catch (_) {}
    }
  }, []);

  // Update TMDb preview mock/fetch
  useEffect(() => {
    if (!tmdbId.trim()) {
      setTmdbPreview(null);
      return;
    }
    const cleanId = tmdbId.trim();
    if (cleanId === '157336') {
      setTmdbPreview({
        id: '157336',
        title: 'Interstellar',
        releaseDate: '2014-11-05',
        overview: 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
        posterUrl: 'https://image.tmdb.org/t/p/w342/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
        mediaType: 'Movie'
      });
    } else if (cleanId === '27205') {
      setTmdbPreview({
        id: '27205',
        title: 'Inception',
        releaseDate: '2010-07-15',
        overview: 'Cobb, a skilled thief who steals corporate secrets through the use of dream-sharing technology, is given the inverse task of planting an idea into the mind of a C.E.O.',
        posterUrl: 'https://image.tmdb.org/t/p/w342/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg',
        mediaType: 'Movie'
      });
    } else if (cleanId === '550') {
      setTmdbPreview({
        id: '550',
        title: 'Fight Club',
        releaseDate: '1999-10-15',
        overview: 'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy.',
        posterUrl: 'https://image.tmdb.org/t/p/w342/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
        mediaType: 'Movie'
      });
    } else {
      setTmdbPreview({
        id: cleanId,
        title: `TMDb Entity #${cleanId}`,
        releaseDate: 'Pending Query',
        overview: 'TMDb API v3 metadata will be retrieved by the Python engine during workflow execution.',
        mediaType: 'Query Scheduled'
      });
    }
  }, [tmdbId]);

  const copyToClipboard = (text: string, keyName: string) => {
    navigator.clipboard.writeText(text);
    setCopiedKey(keyName);
    setTimeout(() => setCopiedKey(null), 2000);
  };

  const handleApplyPreset = (item: typeof PRESET_DEMOS[0]) => {
    setTmdbId(item.id);
    setSourceUrl(item.url);
  };

  // Main Submit Handler for GitHub repository_dispatch
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!tmdbId.trim() || !sourceUrl.trim()) {
      setStatus({
        type: 'error',
        title: 'Missing Required Fields',
        description: 'Please provide both TMDb ID and Source Video URL.',
      });
      return;
    }

    if (!githubPat.trim()) {
      setStatus({
        type: 'error',
        title: 'GitHub PAT Missing',
        description: 'A GitHub Personal Access Token with repo scope is required to dispatch the workflow.',
      });
      return;
    }

    if (!repoOwner.trim() || !repoName.trim()) {
      setStatus({
        type: 'error',
        title: 'Target Repository Unspecified',
        description: 'Please specify the GitHub Repository Owner and Name (e.g. your-username / your-repo).',
      });
      return;
    }

    // Persist credentials
    localStorage.setItem('media_repo_owner', repoOwner.trim());
    localStorage.setItem('media_repo_name', repoName.trim());
    localStorage.setItem('media_repo_pat', githubPat.trim());

    // Step 1: Real-time status "Triggering Engine..."
    setStatus({
      type: 'loading',
      title: 'Triggering Engine...',
      description: `Sending repository_dispatch [event_type: process_video] to ${repoOwner.trim()}/${repoName.trim()}...`,
    });

    const payload = {
      event_type: 'process_video',
      client_payload: {
        tmdb_id: tmdbId.trim(),
        source_url: sourceUrl.trim()
      }
    };

    try {
      const response = await fetch(
        `https://api.github.com/repos/${encodeURIComponent(repoOwner.trim())}/${encodeURIComponent(repoName.trim())}/dispatches`,
        {
          method: 'POST',
          headers: {
            'Accept': 'application/vnd.github.v3+json',
            'Authorization': `Bearer ${githubPat.trim()}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(payload)
        }
      );

      if (response.status === 204) {
        // Step 2: Real-time status "Successfully Queued!"
        setStatus({
          type: 'success',
          title: 'Successfully Queued!',
          description: `The GitHub Actions workflow was successfully triggered. Background container will download, transcode with FFmpeg to H.265, upload to Telegram, and upsert to Supabase.`,
          payload: payload,
          httpCode: 204
        });

        const newHistoryItem: DispatchHistoryItem = {
          id: Math.random().toString(36).substring(2, 9),
          tmdbId: tmdbId.trim(),
          sourceUrl: sourceUrl.trim(),
          timestamp: new Date().toLocaleTimeString(),
          status: 'queued',
          repo: `${repoOwner.trim()}/${repoName.trim()}`,
          message: 'HTTP 204 Dispatched'
        };

        const updated = [newHistoryItem, ...history.slice(0, 19)];
        setHistory(updated);
        localStorage.setItem('media_dispatch_history', JSON.stringify(updated));

      } else {
        // Step 3: Real-time status "Error Details"
        let errorData: any = {};
        try {
          errorData = await response.json();
        } catch (_) {}

        const msg = errorData.message || `HTTP ${response.status} ${response.statusText}`;
        setStatus({
          type: 'error',
          title: 'Error Details',
          description: `GitHub API dispatch failed: ${msg}. Verify your token has 'repo' or 'workflow' scope and that the repository name is accurate.`,
          payload: errorData,
          httpCode: response.status
        });

        const newHistoryItem: DispatchHistoryItem = {
          id: Math.random().toString(36).substring(2, 9),
          tmdbId: tmdbId.trim(),
          sourceUrl: sourceUrl.trim(),
          timestamp: new Date().toLocaleTimeString(),
          status: 'error',
          repo: `${repoOwner.trim()}/${repoName.trim()}`,
          message: msg
        };
        const updated = [newHistoryItem, ...history.slice(0, 19)];
        setHistory(updated);
        localStorage.setItem('media_dispatch_history', JSON.stringify(updated));
      }
    } catch (err: any) {
      setStatus({
        type: 'error',
        title: 'Error Details',
        description: `Network connection error: ${err.message || 'Unable to communicate with GitHub API.'}`,
      });
    }
  };

  // Local Pipeline Dry-Run Simulation
  const runSimulation = () => {
    if (!tmdbId.trim() || !sourceUrl.trim()) {
      setStatus({
        type: 'error',
        title: 'Simulation Parameter Missing',
        description: 'Please input a TMDb ID and Source URL to simulate the transcode sequence.',
      });
      return;
    }

    setIsSimulating(true);
    setSimulationLog([]);

    const steps = [
      `[SIM] Initializing media engine for TMDb ID: ${tmdbId}...`,
      `[SIM] Connecting to TMDb v3 API with TMDB_API_KEY...`,
      `[SIM] Retrieved metadata: ${tmdbPreview?.title || 'Unknown Title'} (${tmdbPreview?.releaseDate || '2024'})`,
      `[SIM] Spawning aria2c 16-connection downloader for ${sourceUrl.substring(0, 48)}...`,
      `[SIM] Download completed (2,410 MB raw stream).`,
      `[SIM] Probing stream geometry: 1920x1080 @ 23.976 fps, audio 5.1 ch`,
      `[SIM] Computing dynamic bitrate target: target < 1.90 GB (1,945,600 KB)`,
      `[SIM] Executing FFmpeg: -c:v libx265 -crf 24 -preset medium -c:a aac -b:a 128k -movflags +faststart`,
      `[SIM] Encoded output size: 1,420 MB (< 2GB Telegram threshold verified)`,
      `[SIM] Uploading stream to Telegram Target Channel ID: -1004408587176...`,
      `[SIM] Telegram API Response: file_id = BAECAANhA... (Message ID: 894)`,
      `[SIM] Connecting to Supabase (https://tmomuyxckjhlsjfbzfvz.supabase.co)...`,
      `[SIM] Querying table 'movies' for tmdb_id = ${tmdbId}...`,
      `[SIM] Performing UPSERT: Appended Telegram stream to 'servers' array & updated 'download_url'.`,
      `[SIM] Process exited with code 0 (SUCCESS).`
    ];

    steps.forEach((line, index) => {
      setTimeout(() => {
        setSimulationLog(prev => [...prev, line]);
        if (index === steps.length - 1) {
          setIsSimulating(false);
          setStatus({
            type: 'success',
            title: 'Simulation Verified',
            description: 'Local dry-run pipeline completed all 6 phases flawlessly.',
          });
        }
      }, (index + 1) * 320);
    });
  };

  const handleDownloadStandalone = () => {
    window.open('/standalone_dashboard.html', '_blank');
  };

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 flex flex-col font-sans">
      {/* 3-Zone Top Bar Contract */}
      <header className="border-b border-slate-800/80 bg-slate-900/60 backdrop-blur sticky top-0 z-30">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 h-16 flex items-center justify-between">
          {/* Zone 1: Single text element wordmark */}
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-indigo-600/20 border border-indigo-500/30 flex items-center justify-center text-indigo-400">
              <Film className="w-4 h-4" />
            </div>
            <div>
              <span className="font-bold tracking-tight text-white text-base">Media Engine</span>
              <span className="text-xs text-slate-400 hidden sm:inline ml-2 border-l border-slate-700 pl-2">Control Console</span>
            </div>
          </div>

          {/* Zone 2: Navigation Links */}
          <nav className="flex items-center gap-1 sm:gap-2">
            <button
              onClick={() => setActiveTab('console')}
              className={`px-3 py-1.5 text-xs font-medium rounded-lg transition-colors whitespace-nowrap ${
                activeTab === 'console'
                  ? 'bg-slate-800 text-white shadow-sm'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              Dispatch Console
            </button>
            <button
              onClick={() => setActiveTab('architecture')}
              className={`px-3 py-1.5 text-xs font-medium rounded-lg transition-colors whitespace-nowrap ${
                activeTab === 'architecture'
                  ? 'bg-slate-800 text-white shadow-sm'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              Secrets & Config
            </button>
            <button
              onClick={() => setActiveTab('files')}
              className={`px-3 py-1.5 text-xs font-medium rounded-lg transition-colors whitespace-nowrap ${
                activeTab === 'files'
                  ? 'bg-slate-800 text-white shadow-sm'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              Repository Files
            </button>
            <button
              onClick={() => setActiveTab('supabase')}
              className={`px-3 py-1.5 text-xs font-medium rounded-lg transition-colors whitespace-nowrap ${
                activeTab === 'supabase'
                  ? 'bg-slate-800 text-white shadow-sm'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              Supabase Schema
            </button>
          </nav>

          {/* Zone 3: Quick Action */}
          <div className="flex items-center gap-3">
            <span className="hidden lg:inline-flex items-center gap-1.5 text-xs font-mono text-slate-400 bg-slate-900 border border-slate-800 px-2.5 py-1 rounded-md">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse"></span>
              TG: -1004408587176
            </span>
            <button
              onClick={handleDownloadStandalone}
              className="text-xs bg-indigo-600 hover:bg-indigo-500 text-white px-3 py-1.5 rounded-lg font-medium transition-colors flex items-center gap-1.5 whitespace-nowrap"
              title="Open standalone zero-dependency HTML file"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Export HTML</span>
            </button>
          </div>
        </div>
      </header>

      {/* Main Container */}
      <main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 py-8">
        {activeTab === 'console' && (
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
            {/* Left 7 Columns: The Main Dispatch Form */}
            <div className="lg:col-span-7 space-y-6">
              <div className="bg-slate-900/80 border border-slate-800/90 rounded-2xl p-6 shadow-xl">
                <div className="flex items-center justify-between pb-5 border-b border-slate-800">
                  <div>
                    <h2 className="text-lg font-semibold text-white">Trigger Workflow Pipeline</h2>
                    <p className="text-xs text-slate-400 mt-0.5">
                      Sends <code className="text-indigo-400 font-mono">repository_dispatch</code> event to GitHub Actions runner
                    </p>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="text-[11px] text-slate-400">Quick Presets:</span>
                    {PRESET_DEMOS.map(p => (
                      <button
                        key={p.id}
                        type="button"
                        onClick={() => handleApplyPreset(p)}
                        className="text-xs bg-slate-800/80 hover:bg-slate-700 text-slate-200 border border-slate-700/60 px-2 py-0.5 rounded transition-colors"
                      >
                        {p.title.split(' ')[0]}
                      </button>
                    ))}
                  </div>
                </div>

                <form onSubmit={handleSubmit} className="mt-6 space-y-5">
                  {/* GitHub Repo Target */}
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 p-4 rounded-xl bg-slate-950/60 border border-slate-800/60">
                    <div>
                      <label className="block text-xs font-medium text-slate-300 mb-1 flex items-center gap-1.5">
                        <Github className="w-3.5 h-3.5 text-slate-400" />
                        GitHub Owner / User
                      </label>
                      <input
                        type="text"
                        value={repoOwner}
                        onChange={(e) => setRepoOwner(e.target.value)}
                        placeholder="e.g. your-github-username"
                        required
                        className="w-full bg-slate-900 border border-slate-700/70 rounded-lg px-3 py-2 text-sm text-slate-100 placeholder-slate-500 focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 transition-colors font-mono"
                      />
                    </div>
                    <div>
                      <label className="block text-xs font-medium text-slate-300 mb-1 flex items-center gap-1.5">
                        <Layers className="w-3.5 h-3.5 text-slate-400" />
                        Repository Name
                      </label>
                      <input
                        type="text"
                        value={repoName}
                        onChange={(e) => setRepoName(e.target.value)}
                        placeholder="e.g. media-processing-engine"
                        required
                        className="w-full bg-slate-900 border border-slate-700/70 rounded-lg px-3 py-2 text-sm text-slate-100 placeholder-slate-500 focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 transition-colors font-mono"
                      />
                    </div>
                  </div>

                  {/* Input Field 1: TMDb Movie/Show ID */}
                  <div>
                    <label className="block text-sm font-semibold text-slate-200 mb-1.5">
                      Input Field 1: TMDb Movie/Show ID
                    </label>
                    <div className="relative">
                      <div className="absolute inset-y-0 left-0 pl-3.5 flex items-center pointer-events-none text-slate-400">
                        <Film className="w-4 h-4" />
                      </div>
                      <input
                        type="text"
                        value={tmdbId}
                        onChange={(e) => setTmdbId(e.target.value)}
                        placeholder="e.g., 157336"
                        required
                        className="w-full bg-slate-950 border border-slate-800 rounded-lg pl-10 pr-24 py-2.5 text-sm text-slate-100 placeholder-slate-500 focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 transition-colors font-mono tabular-nums"
                      />
                      <span className="absolute right-3 top-2.5 text-xs text-slate-500 bg-slate-900 px-2 py-0.5 rounded border border-slate-800">
                        TMDb v3 ID
                      </span>
                    </div>
                    <p className="text-xs text-slate-500 mt-1.5">
                      Engine uses this ID to query TMDb API v3 for Title, Overview, Poster Path, and Release Date.
                    </p>
                  </div>

                  {/* Input Field 2: Direct Source Video URL */}
                  <div>
                    <label className="block text-sm font-semibold text-slate-200 mb-1.5">
                      Input Field 2: Direct Source Video URL
                    </label>
                    <div className="relative">
                      <div className="absolute inset-y-0 left-0 pl-3.5 flex items-center pointer-events-none text-slate-400">
                        <LinkIcon className="w-4 h-4" />
                      </div>
                      <input
                        type="url"
                        value={sourceUrl}
                        onChange={(e) => setSourceUrl(e.target.value)}
                        placeholder="https://example.com/raw_stream_video.mp4"
                        required
                        className="w-full bg-slate-950 border border-slate-800 rounded-lg pl-10 pr-4 py-2.5 text-sm text-slate-100 placeholder-slate-500 focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 transition-colors font-mono"
                      />
                    </div>
                    <p className="text-xs text-slate-500 mt-1.5">
                      Accelerated with yt-dlp & aria2c (16 parallel connections) for maximum bandwidth.
                    </p>
                  </div>

                  {/* Input Field 3: GitHub Personal Access Token (PAT) */}
                  <div>
                    <div className="flex items-center justify-between mb-1.5">
                      <label className="block text-sm font-semibold text-slate-200">
                        Input Field 3: GitHub Personal Access Token (PAT)
                      </label>
                      <a
                        href="https://github.com/settings/tokens/new?scopes=repo"
                        target="_blank"
                        rel="noreferrer"
                        className="text-xs text-indigo-400 hover:text-indigo-300 flex items-center gap-1"
                      >
                        Create PAT <ExternalLink className="w-3 h-3" />
                      </a>
                    </div>
                    <div className="relative">
                      <div className="absolute inset-y-0 left-0 pl-3.5 flex items-center pointer-events-none text-slate-400">
                        <Key className="w-4 h-4" />
                      </div>
                      <input
                        type={showPat ? 'text' : 'password'}
                        value={githubPat}
                        onChange={(e) => setGithubPat(e.target.value)}
                        placeholder="ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
                        required
                        className="w-full bg-slate-950 border border-slate-800 rounded-lg pl-10 pr-16 py-2.5 text-sm text-slate-100 placeholder-slate-500 focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 transition-colors font-mono"
                      />
                      <button
                        type="button"
                        onClick={() => setShowPat(!showPat)}
                        className="absolute right-3 top-2.5 text-xs text-slate-400 hover:text-slate-200 flex items-center gap-1"
                      >
                        {showPat ? <EyeOff className="w-3.5 h-3.5" /> : <Eye className="w-3.5 h-3.5" />}
                        <span>{showPat ? 'Hide' : 'Show'}</span>
                      </button>
                    </div>
                    <p className="text-xs text-slate-500 mt-1.5">
                      Must have <code className="bg-slate-800 px-1 py-0.5 rounded text-slate-300 font-mono">repo</code> scope for repository_dispatch triggers.
                    </p>
                  </div>

                  {/* Action Buttons */}
                  <div className="pt-2 flex flex-col sm:flex-row gap-3">
                    <button
                      type="submit"
                      disabled={status.type === 'loading'}
                      className="flex-1 bg-indigo-600 hover:bg-indigo-500 active:bg-indigo-700 text-white font-semibold py-3 px-6 rounded-xl transition-colors flex items-center justify-center gap-2 shadow-lg shadow-indigo-600/20 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                      {status.type === 'loading' ? (
                        <>
                          <RefreshCw className="w-4 h-4 animate-spin" />
                          <span>Triggering Engine...</span>
                        </>
                      ) : (
                        <>
                          <Send className="w-4 h-4" />
                          <span>PROCESS & SUBMIT</span>
                        </>
                      )}
                    </button>
                    <button
                      type="button"
                      onClick={runSimulation}
                      disabled={isSimulating}
                      className="bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 font-medium py-3 px-5 rounded-xl transition-colors flex items-center justify-center gap-2 whitespace-nowrap text-xs disabled:opacity-50"
                      title="Run an emulated dry-run simulation of the 6-stage pipeline"
                    >
                      <Sparkles className="w-4 h-4 text-indigo-400" />
                      <span>{isSimulating ? 'Simulating...' : 'Dry-Run Simulation'}</span>
                    </button>
                  </div>
                </form>

                {/* Real-time Status Notification Display */}
                {status.type !== 'idle' && (
                  <div
                    className={`mt-6 rounded-xl p-4.5 border transition-all ${
                      status.type === 'loading'
                        ? 'bg-blue-950/30 border-blue-800/80 text-blue-200'
                        : status.type === 'success'
                        ? 'bg-emerald-950/30 border-emerald-800/80 text-emerald-200'
                        : 'bg-rose-950/30 border-rose-800/80 text-rose-200'
                    }`}
                  >
                    <div className="flex items-start gap-3">
                      <div className="mt-0.5 flex-shrink-0">
                        {status.type === 'loading' && <RefreshCw className="w-5 h-5 text-blue-400 animate-spin" />}
                        {status.type === 'success' && <CheckCircle2 className="w-5 h-5 text-emerald-400" />}
                        {status.type === 'error' && <AlertCircle className="w-5 h-5 text-rose-400" />}
                      </div>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center justify-between">
                          <h4 className="font-semibold text-sm">{status.title}</h4>
                          {status.httpCode && (
                            <span className="text-xs font-mono px-2 py-0.5 rounded bg-black/40 border border-white/10">
                              HTTP {status.httpCode}
                            </span>
                          )}
                        </div>
                        <p className="text-xs mt-1 text-slate-300 leading-relaxed">{status.description}</p>

                        {/* Expandable Payload & Action Link */}
                        {status.payload && (
                          <div className="mt-3">
                            <span className="text-[11px] font-mono text-slate-400 block mb-1">Payload Sent:</span>
                            <pre className="font-mono text-[11px] bg-slate-950/90 text-slate-300 p-3 rounded-lg border border-slate-800/80 overflow-x-auto">
                              {JSON.stringify(status.payload, null, 2)}
                            </pre>
                          </div>
                        )}

                        {status.type === 'success' && repoOwner && repoName && (
                          <div className="mt-3 pt-3 border-t border-emerald-800/40 flex items-center justify-between">
                            <span className="text-xs text-emerald-300">View live execution in GitHub Actions:</span>
                            <a
                              href={`https://github.com/${repoOwner}/${repoName}/actions`}
                              target="_blank"
                              rel="noreferrer"
                              className="text-xs font-medium text-white bg-emerald-700/60 hover:bg-emerald-600 px-3 py-1 rounded flex items-center gap-1.5 transition-colors"
                            >
                              Actions Runs <ExternalLink className="w-3 h-3" />
                            </a>
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                )}

                {/* Dry Run Simulation Output Console */}
                {simulationLog.length > 0 && (
                  <div className="mt-6 rounded-xl border border-slate-800 bg-slate-950 p-4 font-mono text-xs">
                    <div className="flex items-center justify-between pb-2 border-b border-slate-800 mb-2">
                      <span className="text-slate-400 flex items-center gap-1.5">
                        <Terminal className="w-3.5 h-3.5 text-indigo-400" />
                        Dry-Run Pipeline Console
                      </span>
                      <button
                        onClick={() => setSimulationLog([])}
                        className="text-[11px] text-slate-500 hover:text-slate-300"
                      >
                        Clear
                      </button>
                    </div>
                    <div className="space-y-1 max-h-56 overflow-y-auto pr-2 text-slate-300 font-mono text-[11px]">
                      {simulationLog.map((log, i) => (
                        <div key={i} className="leading-snug">{log}</div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            </div>

            {/* Right 5 Columns: Movie Preview, Target Specs & Recent History */}
            <div className="lg:col-span-5 space-y-6">
              {/* TMDb Inspector Card */}
              <div className="bg-slate-900/80 border border-slate-800/90 rounded-2xl p-5 shadow-xl">
                <h3 className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-3 flex items-center gap-2">
                  <Film className="w-3.5 h-3.5 text-indigo-400" />
                  TMDb Ingest Preview
                </h3>
                {tmdbPreview ? (
                  <div className="flex gap-4">
                    {tmdbPreview.posterUrl ? (
                      <img
                        src={tmdbPreview.posterUrl}
                        alt={tmdbPreview.title}
                        className="w-20 h-28 object-cover rounded-lg border border-slate-800 flex-shrink-0 shadow-md"
                        referrerPolicy="no-referrer"
                      />
                    ) : (
                      <div className="w-20 h-28 bg-slate-800 rounded-lg border border-slate-700 flex items-center justify-center text-slate-500 flex-shrink-0">
                        <Film className="w-6 h-6" />
                      </div>
                    )}
                    <div className="flex-1 min-w-0">
                      <h4 className="font-semibold text-sm text-white truncate">{tmdbPreview.title}</h4>
                      <div className="flex items-center gap-2 text-xs text-slate-400 mt-1 font-mono">
                        <span>ID: {tmdbPreview.id}</span>
                        <span>·</span>
                        <span>{tmdbPreview.releaseDate}</span>
                      </div>
                      <p className="text-xs text-slate-300 mt-2 line-clamp-3 leading-relaxed">
                        {tmdbPreview.overview}
                      </p>
                    </div>
                  </div>
                ) : (
                  <div className="py-6 text-center text-xs text-slate-500 border border-dashed border-slate-800 rounded-lg">
                    Enter a TMDb Movie/Show ID to preview metadata
                  </div>
                )}
              </div>

              {/* Target Environment Context Card */}
              <div className="bg-slate-900/80 border border-slate-800/90 rounded-2xl p-5 shadow-xl space-y-3.5 text-xs">
                <h3 className="font-semibold text-slate-200 text-sm flex items-center gap-2">
                  <Server className="w-4 h-4 text-indigo-400" />
                  Target Architecture Specs
                </h3>
                <div className="space-y-2 text-slate-300">
                  <div className="flex items-center justify-between p-2 rounded-lg bg-slate-950/60 border border-slate-800/60">
                    <span className="text-slate-400">Telegram Channel</span>
                    <span className="font-mono text-indigo-300">-1004408587176</span>
                  </div>
                  <div className="flex items-center justify-between p-2 rounded-lg bg-slate-950/60 border border-slate-800/60">
                    <span className="text-slate-400">Supabase Endpoint</span>
                    <span className="font-mono text-indigo-300 truncate max-w-[200px]" title="https://tmomuyxckjhlsjfbzfvz.supabase.co">
                      tmomuyxckjhlsjfbzfvz...
                    </span>
                  </div>
                  <div className="flex items-center justify-between p-2 rounded-lg bg-slate-950/60 border border-slate-800/60">
                    <span className="text-slate-400">Transcode Format</span>
                    <span className="font-mono text-slate-200">H.265 / HEVC (&lt; 2GB)</span>
                  </div>
                  <div className="flex items-center justify-between p-2 rounded-lg bg-slate-950/60 border border-slate-800/60">
                    <span className="text-slate-400">Download Engine</span>
                    <span className="font-mono text-slate-200">aria2c (16 parallel streams)</span>
                  </div>
                </div>
              </div>

              {/* Recent Dispatches Log */}
              <div className="bg-slate-900/80 border border-slate-800/90 rounded-2xl p-5 shadow-xl">
                <div className="flex items-center justify-between mb-3">
                  <h3 className="text-xs font-semibold text-slate-400 uppercase tracking-wider flex items-center gap-1.5">
                    <Clock className="w-3.5 h-3.5 text-indigo-400" />
                    Recent Dispatches
                  </h3>
                  {history.length > 0 && (
                    <button
                      onClick={() => {
                        setHistory([]);
                        localStorage.removeItem('media_dispatch_history');
                      }}
                      className="text-[11px] text-slate-500 hover:text-slate-300"
                    >
                      Clear
                    </button>
                  )}
                </div>

                {history.length === 0 ? (
                  <p className="text-xs text-slate-500 py-3 text-center">No dispatches triggered yet.</p>
                ) : (
                  <div className="space-y-2 max-h-60 overflow-y-auto pr-1">
                    {history.map((item) => (
                      <div
                        key={item.id}
                        className="p-2.5 rounded-lg bg-slate-950/60 border border-slate-800/60 flex items-center justify-between text-xs"
                      >
                        <div className="min-w-0 pr-2">
                          <div className="flex items-center gap-2">
                            <span className="font-mono font-medium text-white">TMDb {item.tmdbId}</span>
                            <span
                              className={`text-[10px] font-mono px-1.5 py-0.2 rounded ${
                                item.status === 'queued'
                                  ? 'bg-emerald-950 text-emerald-300 border border-emerald-800/60'
                                  : 'bg-rose-950 text-rose-300 border border-rose-800/60'
                              }`}
                            >
                              {item.status}
                            </span>
                          </div>
                          <p className="text-[11px] text-slate-400 font-mono truncate mt-0.5">{item.sourceUrl}</p>
                        </div>
                        <span className="text-[11px] text-slate-500 font-mono flex-shrink-0">{item.timestamp}</span>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </div>
          </div>
        )}

        {/* Tab 2: Architecture & Secrets Setup */}
        {activeTab === 'architecture' && (
          <div className="space-y-6 max-w-4xl mx-auto">
            <div className="bg-slate-900/80 border border-slate-800/90 rounded-2xl p-6 shadow-xl">
              <h2 className="text-lg font-semibold text-white">GitHub Repository Secrets Setup</h2>
              <p className="text-xs text-slate-400 mt-1">
                To enable the background container to access Telegram, Supabase, and TMDb, configure these 5 secrets in your GitHub repository:
                <code className="text-indigo-400 ml-1">Settings &gt; Secrets and variables &gt; Actions</code>
              </p>

              <div className="mt-6 space-y-3">
                {[
                  {
                    name: 'TELEGRAM_BOT_TOKEN',
                    desc: 'Bot token generated from @BotFather in Telegram',
                    sample: '1234567890:ABCdefGhIJKlmNoPQRstuVWXyz',
                  },
                  {
                    name: 'TELEGRAM_CHANNEL_ID',
                    desc: 'Target Telegram Channel ID as specified in project brief',
                    sample: '-1004408587176',
                  },
                  {
                    name: 'SUPABASE_URL',
                    desc: 'Project Supabase Base URL',
                    sample: 'https://tmomuyxckjhlsjfbzfvz.supabase.co',
                  },
                  {
                    name: 'SUPABASE_SERVICE_ROLE_KEY',
                    desc: 'Service Role Key (bypasses RLS for secure background UPSERT)',
                    sample: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
                  },
                  {
                    name: 'TMDB_API_KEY',
                    desc: 'TMDb API v3 key for metadata extraction (Title, Poster, Overview)',
                    sample: '3a8f9c2d1e0b5a7462819f0e1c2b3a4d',
                  },
                ].map((secret) => (
                  <div
                    key={secret.name}
                    className="p-3.5 rounded-xl bg-slate-950/80 border border-slate-800/80 flex flex-col sm:flex-row sm:items-center justify-between gap-3"
                  >
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="font-mono font-semibold text-xs text-indigo-300">{secret.name}</span>
                        <span className="text-[11px] text-slate-500 font-mono">Secret</span>
                      </div>
                      <p className="text-xs text-slate-400 mt-0.5">{secret.desc}</p>
                      <p className="text-[11px] text-slate-500 font-mono mt-1">Example: {secret.sample}</p>
                    </div>
                    <button
                      onClick={() => copyToClipboard(secret.name, secret.name)}
                      className="self-start sm:self-center px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-mono flex items-center gap-1.5 transition-colors border border-slate-700/60"
                    >
                      {copiedKey === secret.name ? (
                        <>
                          <Check className="w-3.5 h-3.5 text-emerald-400" />
                          <span>Copied</span>
                        </>
                      ) : (
                        <>
                          <Copy className="w-3.5 h-3.5" />
                          <span>Copy Key Name</span>
                        </>
                      )}
                    </button>
                  </div>
                ))}
              </div>
            </div>

            {/* Architecture Pipeline Flow Diagram */}
            <div className="bg-slate-900/80 border border-slate-800/90 rounded-2xl p-6 shadow-xl">
              <h3 className="text-base font-semibold text-white mb-4">Pipeline Execution Lifecycle</h3>
              <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                <div className="p-4 rounded-xl bg-slate-950/80 border border-slate-800/80">
                  <div className="w-7 h-7 rounded-lg bg-indigo-950 border border-indigo-700 text-indigo-400 flex items-center justify-center font-bold text-xs mb-2">1</div>
                  <h4 className="font-semibold text-xs text-white">Repository Dispatch</h4>
                  <p className="text-[11px] text-slate-400 mt-1">Admin Dashboard sends POST request with <code className="text-indigo-300">event_type: process_video</code> to GitHub Actions.</p>
                </div>
                <div className="p-4 rounded-xl bg-slate-950/80 border border-slate-800/80">
                  <div className="w-7 h-7 rounded-lg bg-indigo-950 border border-indigo-700 text-indigo-400 flex items-center justify-center font-bold text-xs mb-2">2</div>
                  <h4 className="font-semibold text-xs text-white">aria2c Download</h4>
                  <p className="text-[11px] text-slate-400 mt-1">GitHub Actions container allocates 16 parallel connections to download the source video stream at maximum speed.</p>
                </div>
                <div className="p-4 rounded-xl bg-slate-950/80 border border-slate-800/80">
                  <div className="w-7 h-7 rounded-lg bg-indigo-950 border border-indigo-700 text-indigo-400 flex items-center justify-center font-bold text-xs mb-2">3</div>
                  <h4 className="font-semibold text-xs text-white">H.265 Transcode</h4>
                  <p className="text-[11px] text-slate-400 mt-1">FFmpeg encodes with <code className="text-indigo-300">libx265</code> with bitrate calculated dynamically to guarantee output is &lt; 2GB.</p>
                </div>
                <div className="p-4 rounded-xl bg-slate-950/80 border border-slate-800/80">
                  <div className="w-7 h-7 rounded-lg bg-indigo-950 border border-indigo-700 text-indigo-400 flex items-center justify-center font-bold text-xs mb-2">4</div>
                  <h4 className="font-semibold text-xs text-white">Telegram & Supabase</h4>
                  <p className="text-[11px] text-slate-400 mt-1">Uploads to Channel ID -1004408587176, extracts file_id, retrieves TMDb metadata, and performs UPSERT into Supabase.</p>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Tab 3: Complete Repository Files Viewer & Exporter */}
        {activeTab === 'files' && (
          <div className="space-y-6 max-w-5xl mx-auto">
            <div className="bg-slate-900/80 border border-slate-800/90 rounded-2xl p-6 shadow-xl">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-800">
                <div>
                  <h2 className="text-lg font-semibold text-white">Repository Files Exporter</h2>
                  <p className="text-xs text-slate-400 mt-0.5">
                    Ready-to-use production files saved in your project workspace for direct GitHub push.
                  </p>
                </div>
                <div className="flex items-center gap-1.5 p-1 rounded-lg bg-slate-950 border border-slate-800">
                  <button
                    onClick={() => setSelectedFileTab('workflow')}
                    className={`px-3 py-1 text-xs rounded font-mono transition-colors ${
                      selectedFileTab === 'workflow' ? 'bg-indigo-600 text-white' : 'text-slate-400 hover:text-slate-200'
                    }`}
                  >
                    .github/workflows/process.yml
                  </button>
                  <button
                    onClick={() => setSelectedFileTab('process_py')}
                    className={`px-3 py-1 text-xs rounded font-mono transition-colors ${
                      selectedFileTab === 'process_py' ? 'bg-indigo-600 text-white' : 'text-slate-400 hover:text-slate-200'
                    }`}
                  >
                    process.py
                  </button>
                  <button
                    onClick={() => setSelectedFileTab('standalone_html')}
                    className={`px-3 py-1 text-xs rounded font-mono transition-colors ${
                      selectedFileTab === 'standalone_html' ? 'bg-indigo-600 text-white' : 'text-slate-400 hover:text-slate-200'
                    }`}
                  >
                    index.html (standalone)
                  </button>
                </div>
              </div>

              {/* Code Viewer Panel */}
              <div className="mt-4">
                <div className="flex items-center justify-between pb-2 mb-2 text-xs text-slate-400">
                  <span className="font-mono">
                    {selectedFileTab === 'workflow' && 'Target: /.github/workflows/process.yml'}
                    {selectedFileTab === 'process_py' && 'Target: /process.py'}
                    {selectedFileTab === 'standalone_html' && 'Target: /standalone_dashboard.html (or /index.html)'}
                  </span>
                  <button
                    onClick={() => {
                      let content = '';
                      if (selectedFileTab === 'workflow') content = GITHUB_WORKFLOW_CODE;
                      else if (selectedFileTab === 'process_py') content = '# Python transcode engine located at /process.py';
                      else content = '<!-- Standalone HTML located at /standalone_dashboard.html -->';
                      copyToClipboard(content, selectedFileTab);
                    }}
                    className="px-2.5 py-1 rounded bg-slate-800 hover:bg-slate-700 text-slate-200 font-mono text-[11px] flex items-center gap-1 transition-colors border border-slate-700/60"
                  >
                    {copiedKey === selectedFileTab ? (
                      <>
                        <Check className="w-3 h-3 text-emerald-400" />
                        <span>Copied</span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-3 h-3" />
                        <span>Copy File Contents</span>
                      </>
                    )}
                  </button>
                </div>

                <div className="bg-slate-950 rounded-xl p-4 border border-slate-800/80 overflow-x-auto max-h-[500px]">
                  <pre className="font-mono text-xs text-slate-300 leading-relaxed">
                    {selectedFileTab === 'workflow' && GITHUB_WORKFLOW_CODE}
                    {selectedFileTab === 'process_py' && `Please refer to /process.py in the project workspace (Python 3.10 with yt-dlp, FFmpeg H.265 transcode, Telegram uploader, TMDb v3 client, and Supabase UPSERT handler).`}
                    {selectedFileTab === 'standalone_html' && `Please refer to /standalone_dashboard.html in the project workspace (Self-contained HTML5 Admin Panel with Tailwind CSS, repository_dispatch trigger, and real-time status banners).`}
                  </pre>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Tab 4: Supabase Schema Configuration */}
        {activeTab === 'supabase' && (
          <div className="space-y-6 max-w-4xl mx-auto">
            <div className="bg-slate-900/80 border border-slate-800/90 rounded-2xl p-6 shadow-xl">
              <div className="flex items-center justify-between pb-4 border-b border-slate-800">
                <div>
                  <h2 className="text-lg font-semibold text-white">Supabase Movies Table Migration SQL</h2>
                  <p className="text-xs text-slate-400 mt-0.5">
                    Run this SQL snippet in your Supabase SQL Editor (<code className="text-indigo-400 font-mono">https://tmomuyxckjhlsjfbzfvz.supabase.co</code>) to create the schema.
                  </p>
                </div>
                <button
                  onClick={() => copyToClipboard(SUPABASE_SCHEMA_SQL, 'supabase_sql')}
                  className="px-3 py-1.5 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold flex items-center gap-1.5 transition-colors"
                >
                  {copiedKey === 'supabase_sql' ? (
                    <>
                      <Check className="w-3.5 h-3.5 text-white" />
                      <span>Copied SQL</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-3.5 h-3.5" />
                      <span>Copy SQL Migration</span>
                    </>
                  )}
                </button>
              </div>

              <div className="mt-4 bg-slate-950 rounded-xl p-4 border border-slate-800/80 overflow-x-auto">
                <pre className="font-mono text-xs text-emerald-400 leading-relaxed">
                  {SUPABASE_SCHEMA_SQL}
                </pre>
              </div>

              <div className="mt-5 p-4 rounded-xl bg-slate-950/60 border border-slate-800 text-xs text-slate-400 space-y-2">
                <h4 className="font-semibold text-slate-200">UPSERT Logic Specification:</h4>
                <ul className="list-disc list-inside space-y-1">
                  <li><strong className="text-slate-300">If tmdb_id exists:</strong> Engine loads existing record, appends the new Telegram CDN server stream URL to the <code className="text-indigo-300">servers</code> JSONB array, and updates <code className="text-indigo-300">download_url</code>.</li>
                  <li><strong className="text-slate-300">If tmdb_id does not exist:</strong> Engine inserts a new complete row with <code className="text-indigo-300">title, overview, poster_path, release_date, servers, download_url</code>.</li>
                </ul>
              </div>
            </div>
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className="border-t border-slate-800/80 bg-slate-950 py-4 mt-auto">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 flex flex-col sm:flex-row items-center justify-between gap-2 text-xs text-slate-500">
          <div className="flex items-center gap-2">
            <span>Media Engine Processing Pipeline</span>
            <span>·</span>
            <span>TMDb API v3</span>
            <span>·</span>
            <span>Supabase Ingest</span>
            <span>·</span>
            <span>Telegram Channel -1004408587176</span>
          </div>
          <div className="font-mono text-[11px] text-slate-500">
            H.265 MP4 &lt; 2GB Target
          </div>
        </div>
      </footer>
    </div>
  );
}
